import { StyleSheet } from "react-native";

const coursesStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#FFFFFF" },
  headerSection: {
    backgroundColor: "#059669",
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  headerContent: {
    gap: 4,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  headerSubtitle: {
    fontSize: 14,
    color: "rgba(255, 255, 255, 0.8)",
    fontWeight: "500",
  },
  container: { padding: 16, gap: 12, paddingBottom: 20 },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#F0F0F0",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 5,
    elevation: 2,
    flexDirection: "column",
  },
  cardImageWrapper: {
    position: "relative",
    overflow: "hidden",
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    height: 160,
    width: "100%",
  },
  cover: {
    width: "100%",
    height: "100%",
    backgroundColor: "#E5E7EB",
  },
  formatBadgeContainer: {
    position: "absolute",
    top: 10,
    left: 10,
    zIndex: 10,
  },
  formatBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    overflow: "hidden",
  },
  formatBadgeText: {
    fontSize: 12,
    fontWeight: "600",
  },
  statusBadgeContainer: {
    position: "absolute",
    top: 10,
    right: 10,
    zIndex: 10,
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: "600",
  },
  cardContent: {
    padding: 12,
    gap: 8,
    width: "100%",
  },
  courseTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#111827",
    lineHeight: 20,
  },
  coachRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  courseCoach: {
    fontSize: 13,
    color: "#6B7280",
    fontWeight: "500",
    flex: 1,
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  locationText: {
    color: "#6B7280",
    fontSize: 12,
    fontWeight: "500",
    flex: 1,
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 2,
  },
  levelBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  levelBadgeText: {
    fontSize: 11,
    fontWeight: "600",
  },
  participantBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F3F4F6",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  participantBadgeText: {
    color: "#6B7280",
    fontSize: 11,
    fontWeight: "600",
  },
  participantInfoSection: {
    backgroundColor: "#F0FDF4",
    padding: 12,
    borderRadius: 10,
    gap: 8,
  },
  participantProgressContainer: {
    gap: 8,
  },
  participantProgressBar: {
    height: 6,
    backgroundColor: "#D1FAE5",
    borderRadius: 3,
    overflow: "hidden",
  },
  participantProgressFill: {
    height: "100%",
    backgroundColor: "#059669",
    borderRadius: 3,
  },
  participantStatsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  participantStat: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  participantStatText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#059669",
  },
  participantStatTextSmall: {
    fontSize: 11,
    fontWeight: "600",
    color: "#6B7280",
  },
  participantDividerSmall: {
    width: 1,
    height: 18,
    backgroundColor: "#D1FAE5",
  },
  searchSection: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
  },
  searchRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  searchBar: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingHorizontal: 14,
    paddingVertical: 11,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 3,
    elevation: 1,
  },
  searchInput: {
    flex: 1,
    color: "#111827",
    fontSize: 14,
    fontWeight: "500",
  },
  filterBtn: {
    width: 44,
    height: 44,
    backgroundColor: "#059669",
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#059669",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  filterSection: { gap: 12, marginBottom: 12 },
  filterSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  filterTitle: {
    color: "#059669",
    fontWeight: "700",
    fontSize: 13,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  filterRow: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  filterSelect: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingHorizontal: 12,
    paddingVertical: 11,
    shadowColor: "#000",
    shadowOpacity: 0.03,
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 2,
    elevation: 1,
  },
  filterSelectDisabled: {
    opacity: 0.5,
    backgroundColor: "#F9FAFB",
  },
  filterSelectText: {
    color: "#111827",
    fontSize: 13,
    flex: 1,
    fontWeight: "500",
  },
  filterSelectPlaceholder: {
    color: "#9CA3AF",
  },
  clearFilterBtn: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: "80%",
    paddingTop: 20,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111827",
  },
  modalLoading: {
    padding: 40,
    alignItems: "center",
  },
  modalItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#F9FAFB",
  },
  modalItemActive: {
    backgroundColor: "#F0FDF4",
  },
  modalItemText: {
    fontSize: 15,
    color: "#111827",
  },
  modalItemTextActive: {
    color: "#059669",
    fontWeight: "600",
  },
  levelBadgeContainer: { flexDirection: "row", gap: 6, flexWrap: "wrap" },
  badge: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8 },
  badgePrimary: { backgroundColor: "#059669" },
  badgeNeutral: { backgroundColor: "#E5E7EB" },
  badgeText: { color: "#FFFFFF", fontSize: 12, fontWeight: "600" },
  priceLabel: {
    color: "#6B7280",
    fontSize: 11,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  price: { color: "#059669", fontWeight: "700", fontSize: 16 },
  primaryBtn: {
    backgroundColor: "#059669",
    borderRadius: 10,
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 20,
    minWidth: 90,
  },
  primaryBtnDisabled: {
    opacity: 0.7,
  },
  primaryBtnText: { color: "#FFFFFF", fontWeight: "700", fontSize: 14 },
  loadMoreBtn: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1.5,
    borderColor: "#059669",
    borderRadius: 10,
    alignItems: "center",
    paddingVertical: 12,
    marginTop: 8,
  },
  loadMoreText: { color: "#059669", fontWeight: "700" },
  detailBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "transparent",
    borderWidth: 1.5,
    borderColor: "#059669",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  detailBtnText: {
    color: "#059669",
    fontWeight: "700",
    fontSize: 14,
  },
  courseModalContent: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: "90%",
    paddingTop: 0,
  },
  courseModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  courseModalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111827",
  },
  closeBtn: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: "#F3F4F6",
    justifyContent: "center",
    alignItems: "center",
  },
  courseDetailContent: {
    padding: 0,
  },
  imageContainer: {
    position: "relative",
    overflow: "hidden",
  },
  courseDetailImage: {
    width: "100%",
    height: 180,
    backgroundColor: "#E5E7EB",
  },
  statusBadgeOverlay: {
    position: "absolute",
    top: 12,
    right: 12,
    flexDirection: "row",
    gap: 8,
    zIndex: 10,
  },
  courseInfoSection: {
    padding: 16,
    gap: 12,
  },
  courseDetailTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111827",
    lineHeight: 24,
  },
  courseDetailCoach: {
    fontSize: 13,
    color: "#6B7280",
    fontWeight: "500",
    marginTop: 4,
  },
  quickInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F9FAFB",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 10,
  },
  quickInfoItem: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  quickInfoText: {
    fontSize: 12,
    color: "#6B7280",
    fontWeight: "500",
    flex: 1,
  },
  divider: {
    width: 1,
    height: 24,
    backgroundColor: "#E5E7EB",
  },
  descriptionSection: {
    backgroundColor: "#F9FAFB",
    borderLeftWidth: 3,
    borderLeftColor: "#059669",
    padding: 12,
    borderRadius: 8,
    gap: 8,
  },
  descriptionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  descriptionTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: "#059669",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  descriptionText: {
    fontSize: 13,
    color: "#111827",
    lineHeight: 18,
    fontWeight: "500",
  },
  detailsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  detailCard: {
    flex: 1,
    minWidth: "47%",
    backgroundColor: "#F9FAFB",
    padding: 10,
    borderRadius: 8,
    gap: 4,
  },
  detailCardLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#059669",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  detailCardValue: {
    fontSize: 14,
    fontWeight: "700",
    color: "#111827",
    lineHeight: 18,
  },
  participantsSection: {
    backgroundColor: "#F0FDF4",
    padding: 12,
    borderRadius: 8,
    gap: 0,
  },
  participantRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
  },
  participantColumn: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
  },
  participantLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#059669",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    marginBottom: 4,
  },
  participantValue: {
    fontSize: 16,
    fontWeight: "700",
    color: "#059669",
  },
  participantDivider: {
    width: 1,
    height: 32,
    backgroundColor: "#C6F6D5",
  },
  individualCourseInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#F0FDF4",
    padding: 12,
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: "#059669",
  },
  individualCourseText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#059669",
  },
  warningSection: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#FEF3C7",
    padding: 12,
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: "#F59E0B",
  },
  warningText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#D97706",
  },
  statusBadgeSection: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 12,
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: "#059669",
  },
  statusDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  statusLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#6B7280",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    marginBottom: 2,
  },
  statusValue: {
    fontSize: 14,
    fontWeight: "700",
  },
  progressSection: {
    backgroundColor: "#F9FAFB",
    padding: 12,
    borderRadius: 8,
    gap: 8,
  },
  progressHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  progressLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: "#059669",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  progressValue: {
    fontSize: 14,
    fontWeight: "700",
    color: "#059669",
  },
  progressBar: {
    height: 6,
    backgroundColor: "#E5E7EB",
    borderRadius: 3,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#059669",
    borderRadius: 3,
  },
  scheduleSection: {
    gap: 8,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#111827",
  },
  scheduleList: {
    gap: 6,
  },
  scheduleItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#F9FAFB",
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
  },
  scheduleDay: {
    fontSize: 12,
    fontWeight: "700",
    color: "#111827",
    minWidth: 50,
  },
  scheduleTime: {
    fontSize: 12,
    color: "#6B7280",
    fontWeight: "500",
    flex: 1,
  },
  moreSchedules: {
    fontSize: 12,
    color: "#6B7280",
    fontWeight: "500",
    fontStyle: "italic",
    textAlign: "center",
    paddingVertical: 6,
  },
  priceSectionLarge: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#F0FDF4",
    padding: 14,
    borderRadius: 10,
    gap: 10,
  },
  priceSectionLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#059669",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  priceSectionValue: {
    fontSize: 20,
    fontWeight: "700",
    color: "#059669",
    marginTop: 2,
  },
  priceInfo: {
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  priceInfoText: {
    fontSize: 11,
    color: "#059669",
    fontWeight: "600",
  },
  registerBtn: {
    flexDirection: "row",
    width: "100%",
    minWidth: "auto",
    marginTop: 4,
    paddingVertical: 12,
    gap: 8,
  },
  disabledBtn: {
    backgroundColor: "#D1D5DB",
  },
  detailCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  detailRowText: {
    fontSize: 13,
    color: "#6B7280",
    fontWeight: "500",
    flex: 1,
  },
  badgesDetailRow: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
  },
});

export default coursesStyles;

